// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQOH3VQc231NezRYBNdebzhVuL1KMX0fY',
    appId: '1:592989854108:web:0024f0e641156deb8bd059',
    messagingSenderId: '592989854108',
    projectId: 'irun-js',
    authDomain: 'irun-js.firebaseapp.com',
    storageBucket: 'irun-js.appspot.com',
    measurementId: 'G-9ZMYG38L7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8XeIYOAvJSRsfGjOpM4N6FPf6YPEk98U',
    appId: '1:592989854108:android:92faaa7ecbf40ce68bd059',
    messagingSenderId: '592989854108',
    projectId: 'irun-js',
    storageBucket: 'irun-js.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZohScjGpy7dB9-keR5NEDyYg0kCi_mA',
    appId: '1:592989854108:ios:4cdbacb37193dfae8bd059',
    messagingSenderId: '592989854108',
    projectId: 'irun-js',
    storageBucket: 'irun-js.appspot.com',
    iosBundleId: 'com.example.irun',
  );
}
